### ISSUE TITLE
Support for HiFiBerry Amp100

### ISSUE THREAD

**Issue by sandeepveldi** [rahul-thakoor/air-pi-play#24]
Hi, I'm currently using an Amp which works perfectly with balena-sound. But when it comes to balena-rpiplay, the only audio output options I see are HDMI and Analog. Please let me know if there's a plan to support Amp.

**Comment by sandeepveldi** [comment]
dtoverlay=hifiberry-amp100

**Comment by rahul-thakoor** [comment]
hey @sandeepveldi balena-rpiplay simply wraps https://github.com/FD-/RPiPlay 
According to https://github.com/FD-/RPiPlay/issues/33 DAC support is tricky and not yet added.
