### ISSUE TITLE
 rpiplay  aacDecoder_DecodeFrame error : 0x4002

### ISSUE THREAD

**Issue by EspenHalvorsen** [rahul-thakoor/air-pi-play#5]
I get  "rpiplay  aacDecoder_DecodeFrame error : 0x4002" in the log, and no streaming happens.

**Comment by rahul-thakoor** [comment]
Hey, i think this is related to https://github.com/FD-/RPiPlay/issues/2

Are you trying to play audio only? Can you try by using the `screen mirroring` option from the control center?

**Comment by EspenHalvorsen** [comment]
Mirroring worked :) So, as I can understand, the other way around is not supported. OK

**Comment by rahul-thakoor** [comment]
Yes. If you only want to cast music i recommend you use [balenaSound](https://hub.balena.io/balenalabs/balenasound)
